### PR TITLE
Dex fixes

### PR DESCRIPTION
**Pull request by wxsBSD**
This fixes the crashes reported on huntr.dev. While there were 5 test cases reported there were only three distinct bugs triggered.

I'll take a look at #950 and #951 tomorrow night but there's a good chance they are already fixed.

### CODE REVIEW

**Comment by wxsBSD** [comment]
Forgot to mention, I fixed some compiler warnings in a previous commit on this branch. Probably should have sent that as a separate PR, sorry for the noise.

**Review by plusvic — APPROVED** [review]

**Comment by JamieSlome** [comment]
@wxsBSD - thanks for your diligence!

When you are ready, are you able to confirm the fix against the [report](https://www.huntr.dev/bounties/007a7784-c211-4847-9cc3-aec38e7d5157/)?

**Comment by wxsBSD** [comment]
I confirmed that all the provided test cases in the report are no longer causing crashes under asan.

**Comment by plusvic** [comment]
@JamieSlome I've updated the report. We'll wait for the reporter's confirmation that he doesn't reproduce the issues anymore with the latest changes.

**Comment by JamieSlome** [comment]
@plusvic - thank you ❤️

**Pull request merged**
