### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sierkb**
Add Apple in section "Who's using YARA", since YARA rules are also used and provided in Apple's recent XProtect (file: XProtect.yara).

### CODE REVIEW

**Comment by plusvic** [comment]
Do you mean that Apple's XProtect uses YARA? If that's true that would be very surprising for me. Any evidence? But in any case, I usually don't include companies in the list unless someone representing the company asks to be included.

**Comment by wxsBSD** [comment]
I can't find anything public but the 10.12 preview has YARA on it, or so I've been told. I've also heard you can add your own signatures to XProtect, but nothing public I can reference.

**Comment by sierkb** [comment]
@plusvic, @wxsBSD:

I use most recent OSX El Capitan (10.11.5). I've discoverd it accidentally after receiving the most recent XProtect-Update (20 Jun 2016, Version 2080) via Software-Update and looking into it.

Have a look at /System/Library/CoreServices/XProtect.bundle/Contents/Resources/
There you will find now 3 files since then (instead of 2):

$ ls -la /System/Library/CoreServices/XProtect.bundle/Contents/Resources/
total 40
drwxr-xr-x  2 root  wheel    170 21 Jun 05:17 .
drwxr-xr-x  4 root  wheel    204 21 Jun 05:17 ..
-rw-r--r--  1 root  wheel   6126 20 Jun 19:54 XProtect.meta.plist
-rw-r--r--  1 root  wheel  68346 20 Jun 19:54 XProtect.plist
**-rw-r--r--  1 root  wheel  21545 20 Jun 19:54 XProtect.yara**



My System:

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.5
BuildVersion:	15F34

$ uname -a
Darwin priamos 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64

**Comment by plusvic** [comment]
Aha! nice discovery @sierkb  :)

I've have the same file in my Mac OS X. It has 99 rules. I'm not including Apple in the list cause nobody from Apple has asked to be included. But it's good to know.

**Comment by sierkb** [comment]
@plusvic: Please close and remove pull request #464 as well (it's an inadvertently dupe of #463).

**Comment by sierkb** [comment]
> I can't find anything public but the 10.12 preview has YARA on it, or so I've been told. I've also heard you can add your own signatures to XProtect, but nothing public I can reference.

Now (April 2020), from Apple itself:

Apple Platform Security: Protecting against malware: XProtect
https://support.apple.com/guide/security/protecting-against-malware-sec469d47bd8/1/web/1

> **XProtect**
>
> macOS includes built-in state-of-the-art antivirus technology called XProtect for the signature-based detection of malware, the use of which supports best-practice protection from viruses and malware. The system uses YARA signatures, which Apple updates regularly. Apple monitors for new malware infections and strains, and updates signatures automatically—independent from system updates—to help defend Mac computers from malware infections. XProtect automatically detects and blocks the execution of known malware. In macOS 10.15 or later, XProtect checks for known malicious content whenever an app:
>
> - Is first launched
> - Has been changed
>
> When XProtect detects known malware, the software is blocked and the user is notified and given the option to move the software to the Trash.

**Pull request closed without merging**
