### PR TITLE
Extra docs for compiling Windows binaries

### PR DESCRIPTION
**Pull request by BitsOfBinary**
Added some extra documentation to detail how to use `configure` to compile Windows binaries.

### CODE REVIEW

**Comment by plusvic** [comment]
Saying that you can run `./configure --host=x86_64-w64-mingw32` in Windows, without explaining which are the pre-requisites are going to be confusing for many people that don't know about mingw32, so I would explain that a little bit about how to setup mingw32 in your machine.

**Comment by BitsOfBinary** [comment]
> Saying that you can run `./configure --host=x86_64-w64-mingw32` in Windows, without explaining which are the pre-requisites are going to be confusing for many people that don't know about mingw32, so I would explain that a little bit about how to setup mingw32 in your machine.

That's a fair comment! My setup was so that I could compile Windows binaries on Linux (using WSL). 

Main reason I want to add these to the docs is that if you're developing YARA on Windows, it wasn't immediately clear on how to compile it from source (I had to check some of the GitHub actions to get some context). Hopefully this addition will make it clear on a method of doing this, but happy to keep tweaking it until it is as clear as possible?

**Comment by plusvic** [comment]
Sure, a more detailed explanation that covers how to build YARA on Windows using Mingw32 is welcome.

**Comment by BitsOfBinary** [comment]
Closing this off as I haven't figured out how to quite make this work yet...

**Pull request closed without merging**
