### PR TITLE
Merge Makefile.am into a single file

### PR DESCRIPTION
**Pull request by hillu**
Benefits
- Changes that result in a rebuild of libyara will also cause test programs to be rebuilt
- Avoid repeating flag definitions

### CODE REVIEW

**Comment by plusvic** [comment]
CIFuzz is failing, it may need to change this path: https://github.com/Oss-fuzz/oss-fuzz/blob/master/projects/yara/build.sh#L30

**Comment by plusvic** [comment]
I tried merging this PR but I'm getting errors like this when running tests:

```
dyld[36973]: symbol not found in flat namespace (_string__finalize)
```

It looks like it's related to linking the tests against the dynamic library instead of the static library.

**Comment by hillu** [comment]
> I tried merging this PR but I'm getting errors like this when running tests:

I suppose we would have seen that right away if we'd had MacOSX CI tests. :-)

**Comment by hillu** [comment]
@plusvic I have been able to reproduce the problem using CI. Investigating …

**Comment by hillu** [comment]
Fixed. The root cause of the problem was the new `string` module.

I had wondered where those `string__something` symbols might come from but otherwise ignored them because of the unfamiliar (to me) messages from the MacOSX dynamic linker. And perhaps because of your assumption about static linking, @plusvic. :-)

Feeling like a total newbie at this "compiling stuff from source" thing right now. ;-)

**Pull request merged**
