### PR TITLE
Improve detection of entry point offset

### PR DESCRIPTION
**Pull request by zavrac**
This commit improves detection of entry point offset in ELF files. If
detection of entry point offset based on section adresses fails,
algorithm iterates over segments and tries to compute offset of entry
point based on segment adresses.

This commit also enables detection of entry point offset in PE files for
other architectures than x86 and x86_64, because my project is focused
also on ARM PE files.

### CODE REVIEW

**Comment by plusvic** [comment]
The use of "entrypoint" keyword in YARA rule is deprecated. This should be implemented in the ELF module (modules/elf.c)

**Comment by zavrac** [comment]
I improve detection of entry point also in ELF module.

**Comment by hillu** [comment]
Can you provide an ELF binary with which the fix can be demonstrated?

**Comment by zavrac** [comment]
I have some ELF binaries that contains only segments, not sections. These binaries are available at https://www.dropbox.com/sh/dinavl46emdndko/AACGxMH5blSMDRgW1foiF2nUa?dl=0

**Comment by plusvic** [comment]
@jacob-baines already did some work to solve this issue in #606. The entry point for the provided files are calculated correctly with the latest code.

**Pull request closed without merging**
