### PR TITLE
fix issue 1394

### PR DESCRIPTION
**Pull request by lprat**
Fix issue: https://github.com/VirusTotal/yara/issues/1394

### CODE REVIEW

**Comment by virusdefender** [comment]
and it seems `symtab_entries` is missing on `elf. ET_DYN ` files as well

**Comment by plusvic** [comment]
`symtab` and `dynsym` are two separate tables, should we have two separate tables in the ELF module as well? I'm not sure what's the better approach, but I'm wondering what happens if an ELF has both `symtab` and  `dynsym`, it that possible? If yes, do they have the same symbols? Wouldn't be confusing to put symbols from `dynsym` in a field named `symtab`?

**Comment by plusvic** [comment]
Closing this PR as #1427 looks like a better alternative.

**Comment by plusvic** [comment]
Implemented in #1427

**Pull request closed without merging**
