### PR TITLE
Fix return-value check of `define_external_variables()` in `cli/yarac.c`. (#1534)

### PR DESCRIPTION
**Pull request by basvs**

### CODE REVIEW

**Comment by basvs** [comment]
@googlebot I signed it!

**Comment by basvs** [comment]
@googlebot I fixed it.

**Comment by basvs** [comment]
Issue is now fixed in https://github.com/VirusTotal/yara/commit/7b5e0a31e78aca558856e690fce5e7412b57849d

Closing pull request

**Comment by plusvic** [comment]
Oh, sorry. I already committed a fix. But thank you vey much for your contribution!

**Comment by basvs** [comment]
No problem. Thanks! :-)

**Pull request closed without merging**
