### PR TITLE
Json module

### PR DESCRIPTION
**Pull request by CaldurG**
I created module for matching json data. It exports function "has_key(str)" and string dictionary "keys". So for json {"hello": "world"} you can just write rule:

import "json"

rule test {
conditon:
json.has_key("hello") and json.keys["hello"] == "world"
}

### CODE REVIEW

**Comment by metthal** [comment]
Pardon me my question, but I wonder, what is the use case for this?

**Comment by CaldurG** [comment]
We are using yara not only to search in executables, but also in malware configs obtained from honeypots and in feed of newly registered certificates. These are all json formatted data so I assumed that maybe this module could also help others.

**Comment by cneberg** [comment]
Would you consider adding some json list operations?    like "len" for lengths of json lists and "contains"  for whether a certain string is a json list?

**Comment by plusvic** [comment]
This module looks interesting, but I've finally decided not to merge it.

**Pull request closed without merging**
