### PR TITLE
Fixed parse problem in cuckoo module for dns_lookup

### PR DESCRIPTION
**Pull request by plutec**
Maybe a change in report.json of cuckoo has become impossible the parse.

### CODE REVIEW

**Comment by plutec** [comment]
the last commits able to show the context of a match, for instance:
```
$ yara -c 3 rule.yar binary 
a binary
Showing 3 lines of context
0x3:$a: hand
0x0: 61 73 20 68 61 6E 64 20 6B 6A 6B 73 68 64 66 6B 	a s   h a n d   k j k s h d f k 
0x10: 6A 73 68 64 66 6B 73 6A 68 64 66 6B 6A 73 68 64 	j s h d f k s j h d f k j s h d 
0x20: 66 6B 6A 73 68 64 66 6B 6A 73 64 68 66 6B 6A 73 	f k j s h d f k j s d h f k j s 

0xa2:$a: hand
0x8c: 6A 64 66 68 6B 6A 73 68 64 66 6B 6A 73 64 68 66 	j d f h k j s h d f k j s d h f 
0x9c: 6B 6A 68 73 64 66 68 61 6E 64 6B 6A 68 73 64 66 	k j h s d f h a n d k j h s d f 
0xac: 6B 6A 68 73 64 66 6B 6A 68 73 64 66 6B 6A 68 73 	k j h s d f k j h s d f k j h s 

0x114:$a: hand
0xe9: 64 66 6B 6A 68 73 64 66 6B 6A 73 68 64 66 6B 6A 	d f k j h s d f k j s h d f k j 
0xf9: 68 73 64 66 6B 6A 68 73 64 66 6B 6A 68 73 64 66 	h s d f k j h s d f k j h s d f 
0x109: 6B 6A 68 73 64 66 6B 6A 68 68 20 68 61 6E 64 0A 	k j h s d f k j h h   h a n d . 
```

**Comment by plusvic** [comment]
Please don't mix two unrelated features in the same pull request. This makes hard to merge one feature without merging the other too.

Regarding the context printing, this solution is quite inefficient. You're mapping and unmapping the file for each match. Besides, this approach doesn't work while scanning process.

**Comment by plutec** [comment]
I tried to do another pull-requests but I could not in github. maybe I had a mistake, sorry.

Regarding the context printing, you are right. I'll try to do another thing more efficient. And I'll make tests with processes. Thanks!

**Comment by plutec** [comment]
I fix the problem mapping and unmapping files. Now it only creates a mmap per file.
Fixed the problem for processes, now look for the block and print the context.

Added a function to free memory blocks created previously.

**Comment by plusvic** [comment]
This is slightly better than the previous commit, but still you are mapping the file or getting the process memory for each matching rule. This can be slow if you have multiple matching rules and large files, while scanning processes is even worse.

In order to implement this properly we need to change the way in which data is passed to the callback from YARA.

**Comment by plusvic** [comment]
Fixed in c6779bbbf6fcd163f6e34a60000193d40f88729c

**Pull request closed without merging**
