### PR TITLE
Fix issue #1443.

### PR DESCRIPTION
**Pull request by plusvic**
As pointed out in the bug report the correct way of aligning the win_cert pointer to the next 8-bytes boundary is not correct. If the previous certificates ends at 0x1234000A, the next one should start at 0x12340010, not at 0x1234000c which is not aligned to 8 bytes.

### CODE REVIEW

**Comment by plusvic** [comment]
@wxsBSD do you have some file with multiple certificates that could be used for a test case?

**Comment by wxsBSD** [comment]
Let me do some digging tonight and see what I can find.

**Comment by wxsBSD** [comment]
7c3f863cbff4db18689d6f0dde31e0f1c320763a30c802490709e166c859d39b has two WIN_CERTIFICATES in it. The first one starts at 0x150ae0 and the second one starts at 0x152ce0.

**Review by wxsBSD — APPROVED** [review]

**Comment by wxsBSD** [comment]
This doesn't seem to affect that one test case I mentioned, but I think it should be right.

**Pull request merged**
