### PR TITLE
Refuse to map procfs files on Linux

### PR DESCRIPTION
**Pull request by hillu**
It makes no sense to try to mmap files for which the filesystem lies about the size (0).

Clsoe #1838 

(It may make sense to consider other pseudo filesystems on Linux and other Unices as well.)

### CODE REVIEW

**Review by plusvic — APPROVED** [review]

**Comment by gwillem** [comment]
This adds a dependency to libmagick, linux/magic.h which complicates cross compilation. @hillu how did you fix this for your own projects?

**Comment by hillu** [comment]
> A dependency to libmagick, linux/magic.h

No, `linux/magic.h` has nothing to do with libmagick; on Debian and derivative distributions, it is shipped as part of `linux-libc-dev`.

"magic" in this case refers to filesystem magic numbers reported by `fstatfs`, we only need `PROC_SUPER_MAGIC` which is part of the Kernel API. So we could get away with this patch:
``` diff
--- a/libyara/filemap.c
+++ b/libyara/filemap.c
@@ -159,7 +159,7 @@ YR_API int yr_filemap_map_fd(
 
 #ifdef __linux__
 #include <sys/vfs.h>
-#include <linux/magic.h>
+#define PROC_SUPER_MAGIC       0x9fa0
 #endif
 
 #define MAP_EXTRA_FLAGS 0
```

**Comment by gwillem** [comment]
Thanks a lot Hillu! Somehow the Go linker keeps adding -lmagic to my build which I assumed was related to the above but I should continue my search. Anyhow, thanks for the patch!

**Comment by gwillem** [comment]
Thanks @plusvic. To clarify, there were two issues:

1. Dep on linux.h, solved by Hillu's patch above. 

2. Unknown origin of -lmagic injection by the Go linker. This was introduced by our upgrade of yara 4.0.2 to 4.3.2. However, we just upgraded to 4.5.1 and our build succeeds. Apologies for reporting an issue with an older version 😅 

(We use https://github.com/hillu/go-yara v4.3, we incorrectly assumed we had to use a corresponding yara version)

**Pull request merged**
